export const FETCH_START = 'RA/FETCH_START';
export const FETCH_END = 'RA/FETCH_END';
export const FETCH_ERROR = 'RA/FETCH_ERROR';
export const FETCH_ERROR_AUTH = 'RA/FETCH_ERROR_AUTH';
export const FETCH_ERROR_VALIDATION = 'RA/FETCH_ERROR_VALIDATION';
export const FETCH_ERROR_HANDLED = 'RA/FETCH_ERROR_HANDLED';
export const FETCH_ERROR_UNHANDLED = 'RA/FETCH_ERROR_UNHANDLED';
export const FETCH_CANCEL = 'RA/FETCH_CANCEL';
