export const FETCH_START = 'RA/FETCH_START';
export const FETCH_END = 'RA/FETCH_END';
export const FETCH_ERROR = 'RA/FETCH_ERROR';
export const FETCH_ERROR_REJECTED = 'RA/FETCH_ERROR_HANDLED';
export const FETCH_ERROR_RESOLVED = 'RA/FETCH_ERROR_UNHANDLED';
export const FETCH_CANCEL = 'RA/FETCH_CANCEL';
