import { TranslationMessages } from 'ra-core';

const japaneseMessages: TranslationMessages = {
    ra: {
        action: {
            add_filter: 'フィルターを追加',
            add: '追加',
            back: '戻る',
            bulk_actions: '1つのアイテムが選択されました |||| %{smart_count} アイテムが選択されました',
            cancel: 'キャンセル',
            clear_array_input: 'リストをクリア',
            clear_input_value: '値をクリア',
            clone: '複製',
            confirm: '確認',
            create: '作成',
            create_item: '%{item}を作成',
            delete: '削除',
            edit: '編集',
            export: 'エクスポート',
            list: 'リスト',
            refresh: 'リフレッシュ',
            remove_filter: 'このフィルターを削除',
            remove_all_filters: 'すべてのフィルターを削除',
            remove: '削除',
            save: '保存',
            search: '検索',
            select_all: 'すべて選択',
            select_row: 'この行を選択',
            show: '表示',
            sort: 'ソート',
            undo: '元に戻す',
            unselect: '選択解除',
            expand: '展開',
            close: '閉じる',
            open_menu: 'メニューを開く',
            close_menu: 'メニューを閉じる',
            update: '更新',
            move_up: '上へ移動',
            move_down: '下へ移動',
            open: '開く',
            toggle_theme: 'テーマ切り替え',
            select_columns: '列',
            update_application: 'アプリケーションを再読み込み',
        },
        boolean: {
            true: 'はい',
            false: 'いいえ',
            null: ' ',
        },
        page: {
            create: '%{name}を作成',
            dashboard: 'ダッシュボード',
            edit: '%{name} %{recordRepresentation}を編集',
            error: '何か問題が発生しました',
            list: '%{name}',
            loading: '読み込み中',
            not_found: '見つかりません',
            show: '%{name} %{recordRepresentation}を表示',
            empty: '%{name}はまだありません。',
            invite: '追加しますか？',
        },
        input: {
            file: {
                upload_several: 'アップロードするファイルをドロップまたは選択してください。',
                upload_single: 'アップロードするファイルをドロップまたは選択してください。',
            },
            image: {
                upload_several: 'アップロードする画像をドロップまたは選択してください。',
                upload_single: 'アップロードする画像をドロップまたは選択してください。',
            },
            references: {
                all_missing: '参照データが見つかりません。',
                many_missing: '関連する参照の少なくとも1つが利用できなくなっているようです。',
                single_missing: '関連する参照が利用できなくなっているようです。',
            },
            password: {
                toggle_visible: 'パスワードを非表示にする',
                toggle_hidden: 'パスワードを表示する',
            },
        },
        message: {
            about: '詳細',
            are_you_sure: '本当によろしいですか？',
            auth_error: '認証トークンの検証中にエラーが発生しました。',
            bulk_delete_content: 'この%{name}を削除してもよろしいですか？ |||| これらの%{smart_count} アイテムを削除してもよろしいですか？',
            bulk_delete_title: '%{name}を削除 |||| %{smart_count} 個の%{name}を削除',
            bulk_update_content: 'この%{name}を更新してもよろしいですか？ |||| これらの%{smart_count} アイテムを更新してもよろしいですか？',
            bulk_update_title: '%{name}を更新 |||| %{smart_count} 個の%{name}を更新',
            clear_array_input: 'リスト全体をクリアしてもよろしいですか？',
            delete_content: 'このアイテムを削除してもよろしいですか？',
            delete_title: '%{name} #%{id}を削除',
            details: '詳細',
            error: 'クライアントエラーが発生し、リクエストを完了できませんでした。',
            invalid_form: 'フォームが無効です。エラーを確認してください。',
            loading: 'ページが読み込まれています。しばらくお待ちください。',
            no: 'いいえ',
            not_found: 'URLを間違えたか、誤ったリンクをたどりました。',
            yes: 'はい',
            unsaved_changes: '一部の変更が保存されませんでした。無視してもよろしいですか？',
        },
        navigation: {
            no_results: '結果が見つかりません',
            no_more_results: 'ページ番号%{page}は範囲外です。前のページを試してください。',
            page_out_of_boundaries: 'ページ番号%{page}は範囲外です',
            page_out_from_end: '最後のページの後には移動できません',
            page_out_from_begin: '1ページ目の前には移動できません',
            page_range_info: '%{offsetBegin}-%{offsetEnd} / 全%{total} 件',
            partial_page_range_info: '%{offsetBegin}-%{offsetEnd} / 全%{offsetEnd} 件以上',
            current_page: 'ページ %{page}',
            page: 'ページ %{page} へ移動',
            first: '最初のページへ移動',
            last: '最後のページへ移動',
            next: '次のページへ移動',
            previous: '前のページへ移動',
            page_rows_per_page: '1ページあたりの行数:',
            skip_nav: 'コンテンツへスキップ',
        },
        sort: {
            sort_by: '%{field} %{order} で並べ替え',
            ASC: '昇順',
            DESC: '降順',
        },
        auth: {
            auth_check_error: '続行するにはログインしてください',
            user_menu: 'プロフィール',
            username: 'ユーザー名',
            password: 'パスワード',
            sign_in: 'サインイン',
            sign_in_error: '認証に失敗しました。もう一度試してください。',
            logout: 'ログアウト',
        },
        notification: {
            updated: '要素が更新されました |||| %{smart_count} 件の要素が更新されました',
            created: '要素が作成されました',
            deleted: '要素が削除されました |||| %{smart_count} 件の要素が削除されました',
            bad_item: '不正な要素',
            item_doesnt_exist: '要素は存在しません',
            http_error: 'サーバー通信エラー',
            data_provider_error: 'データプロバイダエラー。詳細はコンソールを確認してください。',
            i18n_error: '指定された言語の翻訳を読み込めません',
            canceled: 'アクションがキャンセルされました',
            logged_out: 'セッションが終了しました。再接続してください。',
            not_authorized: 'このリソースへのアクセス権がありません。',
            application_update_available: '新しいバージョンが利用可能です。',
        },
        validation: {
            required: '必須',
            minLength: '%{min} 文字以上である必要があります',
            maxLength: '%{max} 文字以下である必要があります',
            minValue: '%{min} 以上である必要があります',
            maxValue: '%{max} 以下である必要があります',
            number: '数値である必要があります',
            email: '有効なメールアドレスである必要があります',
            oneOf: '以下のいずれかである必要があります: %{options}',
            regex: '特定の形式（正規表現）と一致する必要があります: %{pattern}',
            unique: '一意である必要があります',
        },
        saved_queries: {
            label: '保存されたクエリ',
            query_name: 'クエリ名',
            new_label: '現在のクエリを保存...',
            new_dialog_title: '現在のクエリを名前を付けて保存',
            remove_label: '保存されたクエリを削除',
            remove_label_with_name: '"%{name}" クエリを削除',
            remove_dialog_title: '保存されたクエリを削除しますか？',
            remove_message: 'このアイテムを保存されたクエリのリストから削除してもよろしいですか？',
            help: 'リストをフィルターし、このクエリを後で保存します',
        },
        configurable: {
            customize: 'カスタマイズ',
            configureMode: 'このページを設定',
            inspector: {
                title: 'インスペクタ',
                content: 'アプリケーションUI要素をホバーして構成します',
                reset: '設定をリセット',
                hideAll: 'すべて非表示',
                showAll: 'すべて表示',
            },
            Datagrid: {
                title: 'データグリッド',
                unlabeled: 'ラベルなしの列 #%{column}',
            },
            SimpleForm: {
                title: 'フォーム',
                unlabeled: 'ラベルなしの入力 #%{input}',
            },
            SimpleList: {
                title: 'リスト',
                primaryText: '主要テキスト',
                secondaryText: 'セカンダリテキスト',
                tertiaryText: '第三テキスト',
            },
        },
    },
};

export default japaneseMessages;
